name: 'build-kotlin-micronaut-maven'
on:
  push:
    branches:
    - main
  pull_request:
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2    
      - name: Build with Maven
         run: mvn -B clean install
      - name: Lint
         run: mvn antrun:run@ktlint
      - name: Sonar    
         run: mvn sonar:sonar \
              -Dsonar.projectKey=kotlin-micronaut \
              -Dsonar.host.url=http://ec2-34-227-47-177.compute-1.amazonaws.com:9000 \
              -Dsonar.login=${{ secrets.SONAR_TOKEN }}
      - name: Horusec Security
          run: |
            curl -fsSL https://horusec-cli.s3.amazonaws.com/install.sh | bash
            horusec start -p ./
