name: 'build-kotlin-micronaut-maven'
on:
  push:
    branches:
      - dev
  pull_request:
jobs:
  authenticate:
    runs-on: self-hosted
      outputs:
        ecr_pwd: ${{ steps.step1.outputs.ecr_pwd }}
      steps:
        - id: step1
          run: |
            ECR_PWD=`aws ecr get-login-password --region us-east-1`
            echo "::set-output name=ecr_pwd::$ECR_PWD"

  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('./pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build
        run: mvn -B clean install
        working-directory: ./
      - name: Lint
        run: mvn antrun:run@ktlint
        working-directory: ./

  quality:
    - steps:
      - name: Sonar
        run: mvn sonar:sonar
          -Dsonar.projectKey=kotlin-micronaut
          -Dsonar.host.url=http://ec2-54-163-196-183.compute-1.amazonaws.com:9000
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        working-directory: ./
      - name: Horusec Security
        run: |
          curl -fsSL https://horusec-cli.s3.amazonaws.com/install.sh | bash
          horusec start -p ./
        working-directory: ./