name: 'build-kotlin-micronaut-maven'
on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('./pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build
        run: mvn -B clean install
        working-directory: ./
      - name: Lint
        run: mvn antrun:run@ktlint
        working-directory: ./
      - uses: actions/cache@v1
        with:
          path: ~/target/demo-*.jar
          key: ${{ github.sha }}-dev-jar

  quality:
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Sonar
        run: mvn sonar:sonar
          -Dsonar.projectKey=kotlin-micronaut
          -Dsonar.host.url=http://ec2-54-163-196-183.compute-1.amazonaws.com:9000
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        working-directory: ./
  
  security:
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Horusec Security
        run: |
          curl -fsSL https://horusec-cli.s3.amazonaws.com/install.sh | bash
          horusec start -p ./
        working-directory: ./

  authenticate:
    runs-on: self-hosted
    needs: [quality,security]
    outputs:
      ecr_pwd: ${{ steps.step1.outputs.ecr_pwd }}
    steps:
      - id: step1
        run: |
          ECR_PWD=`aws ecr get-login-password --region us-east-1` 
          echo "::set-output name=ecr_pwd::$ECR_PWD"

  docker_build:
    runs-on: self-hosted
    needs: [authenticate]
    container:
      image: 475383224204.dkr.ecr.us-east-1.amazonaws.com/step-image-docker:latest
      credentials:
        username: AWS
        password: ${{ needs.authenticate.outputs.ecr_pwd }}
    steps:
      - uses: actions/cache@v1
        with:
          path: ~/target/demo-*.jar
          key: ${{ github.sha }}-dev-jar
      - name: Publish docker image
        run: docker build . -t 475383224204.dkr.ecr.us-east-1.amazonaws.com/micronaut-demo:dev

  docker_push:
    runs-on: self-hosted
    needs: [authenticate,docker_build]
    container:
      image: 475383224204.dkr.ecr.us-east-1.amazonaws.com/step-image-docker:latest
      credentials:
        username: AWS
        password: ${{ needs.authenticate.outputs.ecr_pwd }}
    steps:
      - name: Login docker
        run: docker login --username AWS --password ${{ needs.authenticate.outputs.ecr_pwd }} 475383224204.dkr.ecr.us-east-1.amazonaws.com
      - name: Publish docker image
        run: docker push 475383224204.dkr.ecr.us-east-1.amazonaws.com/micronaut-demo:dev