name: 'build-kotlin-micronaut-maven'
on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  aws-login:
    runs-on: self-hosted
    outputs:
      ecr_pwd: ${{ steps.ecrpassword.outputs.ecr_pwd }}
      kube_config: ${{ steps.kubeconfig.outputs.kube_config }}
    steps:
      - id: ecrpassword
        run: |
          ECR_PWD=`aws ecr get-login-password --region us-east-1` 
          echo "::set-output name=ecr_pwd::$ECR_PWD"
      - name: Generate kube_config
        run: aws eks --region us-east-1 update-kubeconfig --name orange-pipes-sandbox --role-arn arn:aws:iam::475383224204:role/TesteEliasGithubRunner
      - id: kubeconfig
        name: "Generate kubeconfig"
        run: |
          KUBE_CONFIG=`cat $HOME/.kube/config | base64 -w 0`
          echo "::set-output name=kube_config::$KUBE_CONFIG"

  build:
    runs-on: self-hosted
    needs: aws-login
    container:
      image: 475383224204.dkr.ecr.us-east-1.amazonaws.com/step-image-java11-maven:latest
      credentials:
        username: AWS
        password: ${{ needs.aws-login.outputs.ecr_pwd }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('./pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build
        run: mvn -B clean install
        working-directory: ./
      - name: Lint
        run: mvn antrun:run@ktlint
        working-directory: ./
      - uses: actions/cache@v1
        with:
          path: target/demo-*.jar
          key: ${{ github.sha }}-dev-jar

  quality:
    runs-on: self-hosted
    needs: [aws-login,build]
    container:
      image: 475383224204.dkr.ecr.us-east-1.amazonaws.com/step-image-java11-maven:latest
      credentials:
        username: AWS
        password: ${{ needs.aws-login.outputs.ecr_pwd }}
    steps:
      - name: Sonar
        run: mvn sonar:sonar
          -Dsonar.projectKey=kotlin-micronaut
          -Dsonar.host.url=http://ec2-54-163-196-183.compute-1.amazonaws.com:9000
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        working-directory: ./
  
  security:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Horusec Security
        run: |
          curl -fsSL https://horusec-cli.s3.amazonaws.com/install.sh | bash
          horusec start -p ./
        working-directory: ./

  docker_build:
    runs-on: self-hosted
    needs: [aws-login,quality,security]
    container:
      image: 475383224204.dkr.ecr.us-east-1.amazonaws.com/step-image-docker:latest
      credentials:
        username: AWS
        password: ${{ needs.aws-login.outputs.ecr_pwd }}
    steps:
      - uses: actions/cache@v1
        with:
          path: target/demo-*.jar
          key: ${{ github.sha }}-dev-jar
      - name: Build docker image
        run: docker build . -t 475383224204.dkr.ecr.us-east-1.amazonaws.com/micronaut-demo:dev

  docker_push:
    runs-on: self-hosted
    needs: [aws-login,docker_build]
    container:
      image: 475383224204.dkr.ecr.us-east-1.amazonaws.com/step-image-docker:latest
      credentials:
        username: AWS
        password: ${{ needs.aws-login.outputs.ecr_pwd }}
    steps:
      - name: Login docker
        run: docker login --username AWS --password ${{ needs.aws-login.outputs.ecr_pwd }} 475383224204.dkr.ecr.us-east-1.amazonaws.com
      - name: Publish docker image
        run: docker push 475383224204.dkr.ecr.us-east-1.amazonaws.com/micronaut-demo:dev

  deploy-eks:
    name: 'Deploy to EKS'
    runs-on: self-hosted
    needs: [build-image, aws-login]
    container:
      image: 475383224204.dkr.ecr.us-east-1.amazonaws.com/step-image-deploy-eks:latest
      credentials:
        username: AWS
        password: ${{ needs.aws-login.outputs.ecr_password }}
      env:
        KUBE_CONFIG: ${{ needs.aws-login.outputs.kube_config }}
        APP_NAME: micronaut-demo
        APP_IMAGE: micronaut-demo:latest
    steps:
      - name: Add sandbox k8s cluster to hosts
        run: echo "54.87.1.134 DDED8C1BC51F2D4FC42588C3425440F1.gr7.us-east-1.eks.amazonaws.com" >> /etc/hosts
      - name: Kubectl deploy
        run: sh /orange-init.sh